/** @type {import('tailwindcss').Config} */
import typography from '@tailwindcss/typography';

export default {
  content: [
    './src/**/*.{astro,html,js,jsx,ts,tsx,vue,svelte}',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#eff6ff',
          100: '#dbeafe',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          900: '#1e3a8a',
        },
        profit: '#16a34a',
        loss: '#dc2626',
        muted: '#6b7280',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
    },
    typography: ({ theme }) => ({
      DEFAULT: {
        css: {
          '--tw-prose-body': theme('colors.gray.800'),
          '--tw-prose-headings': theme('colors.gray.900'),
          '--tw-prose-links': theme('colors.brand.600'),
          '--tw-prose-bold': theme('colors.gray.900'),
          '--tw-prose-code': theme('colors.pink.700'),
          '--tw-prose-quotes': theme('colors.gray.700'),
          '--tw-prose-quote-borders': theme('colors.brand.500'),
          '--tw-prose-counters': theme('colors.gray.500'),
          '--tw-prose-bullets': theme('colors.gray.400'),
          '--tw-prose-hr': theme('colors.gray.200'),
          '--tw-prose-th-borders': theme('colors.gray.300'),
          '--tw-prose-td-borders': theme('colors.gray.200'),
          maxWidth: 'none',
          fontSize: '0.95rem',
          lineHeight: '1.75',
          p: { marginTop: '1.25em', marginBottom: '1.25em' },
          h1: {
            fontWeight: '700',
            fontSize: '1.875rem',
            lineHeight: '2.25rem',
            marginTop: '2em',
            marginBottom: '1em',
            paddingBottom: '0.5em',
            borderBottom: `2px solid ${theme('colors.gray.200')}`,
          },
          h2: {
            fontWeight: '700',
            fontSize: '1.5rem',
            lineHeight: '2rem',
            marginTop: '1.75em',
            marginBottom: '0.75em',
            paddingBottom: '0.4em',
            borderBottom: `1px solid ${theme('colors.gray.200')}`,
          },
          h3: {
            fontWeight: '600',
            fontSize: '1.25rem',
            lineHeight: '1.75rem',
            marginTop: '1.5em',
            marginBottom: '0.5em',
            color: theme('colors.brand.700'),
          },
          h4: {
            fontWeight: '600',
            fontSize: '1.05rem',
            marginTop: '1.25em',
            marginBottom: '0.5em',
            color: theme('colors.gray.800'),
          },
          a: {
            textDecoration: 'underline',
            textDecorationThickness: '1px',
            textUnderlineOffset: '2px',
            fontWeight: '500',
          },
          'a:hover': {
            color: theme('colors.brand.700'),
            textDecorationThickness: '2px',
          },
          code: {
            fontWeight: '600',
            backgroundColor: theme('colors.gray.100'),
            padding: '0.15rem 0.4rem',
            borderRadius: '0.25rem',
            fontSize: '0.875em',
            border: `1px solid ${theme('colors.gray.200')}`,
          },
          'code::before': { content: 'none' },
          'code::after': { content: 'none' },
          pre: {
            backgroundColor: '#f6f8fa',
            borderRadius: '0.5rem',
            padding: '1rem 1.25rem',
            border: `1px solid ${theme('colors.gray.200')}`,
            fontSize: '0.875em',
            lineHeight: '1.65',
            marginTop: '1.5em',
            marginBottom: '1.5em',
          },
          'pre code': {
            backgroundColor: 'transparent',
            border: 'none',
            padding: '0',
            fontWeight: '400',
            color: 'inherit',
            fontSize: 'inherit',
          },
          table: {
            width: '100%',
            fontSize: '0.9em',
            marginTop: '1.5em',
            marginBottom: '1.5em',
            borderCollapse: 'collapse',
          },
          thead: {
            borderBottomWidth: '2px',
            borderBottomColor: theme('colors.gray.300'),
            backgroundColor: theme('colors.gray.50'),
          },
          'thead th': {
            fontWeight: '600',
            textAlign: 'left',
            color: theme('colors.gray.700'),
            padding: '0.65rem 0.85rem',
            borderBottom: `2px solid ${theme('colors.gray.300')}`,
          },
          'tbody td': {
            padding: '0.65rem 0.85rem',
            borderBottom: `1px solid ${theme('colors.gray.200')}`,
            verticalAlign: 'top',
          },
          'tbody tr:last-child td': {
            borderBottom: 'none',
          },
          'tbody tr:hover': {
            backgroundColor: theme('colors.gray.50'),
          },
          ul: {
            marginTop: '1em',
            marginBottom: '1em',
            paddingLeft: '1.5em',
            listStyleType: 'disc',
          },
          'ul li': {
            marginTop: '0.4em',
            marginBottom: '0.4em',
            paddingLeft: '0.25em',
          },
          ol: {
            marginTop: '1em',
            marginBottom: '1em',
            paddingLeft: '1.5em',
            listStyleType: 'decimal',
          },
          'ol li': {
            marginTop: '0.4em',
            marginBottom: '0.4em',
            paddingLeft: '0.25em',
          },
          'ul ul, ol ul, ul ol, ol ol': {
            marginTop: '0.4em',
            marginBottom: '0.4em',
          },
          blockquote: {
            fontStyle: 'normal',
            borderLeftWidth: '4px',
            borderLeftColor: theme('colors.brand.500'),
            backgroundColor: theme('colors.brand.50'),
            padding: '0.75rem 1rem',
            marginTop: '1.5em',
            marginBottom: '1.5em',
            borderRadius: '0 0.375rem 0.375rem 0',
          },
          'blockquote p': {
            marginTop: '0.5em',
            marginBottom: '0.5em',
          },
          hr: {
            marginTop: '2.5em',
            marginBottom: '2.5em',
            borderColor: theme('colors.gray.200'),
          },
          img: {
            marginTop: '1.5em',
            marginBottom: '1.5em',
            borderRadius: '0.5rem',
            border: `1px solid ${theme('colors.gray.200')}`,
          },
        },
      },
    }),
  },
  plugins: [typography],
};
